---
title: A Python Post?
author: Adam
date: '2018-03-27'
slug: a-python-post
categories:
  - Machine Learning
  - Python
tags:
  - Python
  - Random Forests
  - Machine Learning
---

This isn't a typical post. Though I prefer working in R, I also do quite a bit of work in Python these days.
I really like the way Python is setup for machine learning and there are some deep learning focused
packages that just don't exist on R yet. One of these is a package called [Fastai](https://github.com/fastai/fastai). Fastai is a python 
package that wraps the Pytorch deep learning library from Facebook. I learned about it while taking
the Fastai [MOOC's](http://course.fast.ai/) on machine learning and deep learning and I've wanted to play around with it myself ever since.

To give it a whirl, I spent some time building a Kaggle Kernal that uses the Fastai package(along with sklearn)
to build a random forest to predict interview attendence. While I know there are ways to integrate both Python
and R posts into a blog, since I currently blog using blogdown from R, I'm still figuring out the details 
behind posting a Python notebook here.  For now though, I'll link to my Kaggle Kernal and apologize for the janky 
work-around. 

Anyway, you can find the kernal [here](https://www.kaggle.com/athoul01/predicting-interview-attendence). Enjoy!